# Generated by Django 3.2.23 on 2023-12-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='time',
        ),
    ]
