# Generated by Django 3.2.23 on 2023-12-05 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_remove_interaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
